% -------------------------------------------------------------------
%  Generated by MATLAB on 22-Jun-2023 22:17:12
%  MATLAB version: 9.10.0.2015706 (R2021a) Update 7
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

policy = saveVarsMat.policy; % <1x1 struct> unsupported class at policy.fcn

clear saveVarsMat;
